### ISSUE TITLE
Cannot add other accounts?

### ISSUE THREAD

**Issue by JohannesWiesner** [uptechteam/default.wtf#20]
Hi there, first of all thanks for this wonderful extension! I found your extension while [browsing through this stackoverflow post](https://webapps.stackexchange.com/questions/49752/specify-default-google-account-for-different-products). I installed it, but I don't find any option to add other google accounts? Am I supposed to manually add them? I only can see the google account with which I am currently logged in.

Greetings,

Johannes

**Comment by JohannesWiesner** [comment]
That's strange, today I tried again and suddenly I can see all other accounts.

**Comment by JohannesWiesner** [comment]
And now it's happening again. Sometimes the other accounts simply do not appear when you click on the extension. Is there any logic of what has to be done in order to get DefaultGoogleAccount having all accounts in scope? I assume it has to do something with logging in / logging out / being logged in with different accounts at the same time. What exactly has to be done with regards to the settings in chrome so that Default Google Account works properly?

**Comment by AndriyBas** [comment]
@JohannesWiesner The extension pulls your existing logged in account from Google. for extension to see them, log into them in any Google service (for example, Gmail), refresh the page, and the extension should see them.
