### ISSUE TITLE
Doesn't work instantly on launch

### ISSUE THREAD

**Issue by Techy05** [uptechteam/default.wtf#21]
The extension works perfectly fine if chrome is already open, and you open a link from within chrome or any external app.
But if chrome is not open, and you open a link from another app, it doesn't work (You have to refresh the website then it works)
I only use for meet and classroom. I don't know why this happens. Or maybe I am doing something wrong?

**Comment by AndriyBas** [comment]
@Techy05 it does work when opening the link from external app. 
For example, when I open the Google Meet app, it redirects me to the correct account.
It can be that your URL already has the account specified, like "https://meet.google.com/nfw-mzoz-zjs?authuser=1"
In that case the extension respects the already specified account, and does not redirect. 
If the link is without the account, like "https://meet.google.com/nfw-mzoz-zjs" — the extension would redirect to your specified default account.
