### ISSUE TITLE
alt {num} keybinds not customisable

### ISSUE THREAD

**Issue by AlbertBaubleDeem** [uptechteam/default.wtf#22]
I cannot use alt {1-4} for writing symbols while using the extension as it keeps them for its own use. There is no option in GUI to customise keybinds or turn them off all together.

**Comment by AndriyBas** [comment]
@CodingAlbert you can edit or disable these extension shortcuts by going to the Shortcut settings, at "chrome://extensions/shortcuts" in your browser
