### ISSUE TITLE
Google Developer Profile

### ISSUE THREAD

**Issue by Titos23** [uptechteam/default.wtf#24]
Hello. Congratulations for your work. Can you please add a posibility to set a rule for the google developer account on the codelab pages ?

**Comment by AndriyBas** [comment]
@Titos23 we'll add support for "developers.google.com" in the new release. 
What developer account were you looking for?

**Comment by Titos23** [comment]
I'm lost when you ask which developer account I was looking for. Are there multiple types of developer account ?

**Comment by AndriyBas** [comment]
@Titos23 I mean if you had in mind other google services to support? (apart from "developers.google.com")

**Comment by Titos23** [comment]
Okay. Apart from that, I have nothing in mind.
