### ISSUE TITLE
Allow to remove users

### ISSUE THREAD

**Issue by JohannesWiesner** [uptechteam/default.wtf#25]
Hi, 

I accidentally logged in with another gmail account. Now this account appears in the hierarchy under 2) third.account@gmail.com and "pushed" down my actual second account to 3) second.account@gmail.com

I cannot see any option to undo this or to delete this account?

**Comment by AndriyBas** [comment]
You need to log out from Google Services from that account.

**Comment by AndriyBas** [comment]
or log out from all accounts, and then log back in from the ones you want to use
